### ISSUE TITLE
Error to load pretrained weight

### ISSUE THREAD

**Issue by freaky-geeky** [JaidedAI/Easy_OCR#9]
Observed the Easy_OCR engine throwing error during the loading process of the pre-trained model. Please find the below error logs,

```
Traceback (most recent call last):
  File "/home/ironman/Workshop/GitDrawer/Easy_OCR/ocr_test.py", line 3, in <module>
    reader = easy_ocr.Reader(['ja'])
  File "/home/ironman/Workshop/GitDrawer/Easy_OCR/easy_ocr/easy_ocr.py", line 145, in __init__
    dict_list, MODEL_PATH, device = self.device)
  File "/home/ironman/Workshop/GitDrawer/Easy_OCR/easy_ocr/recognition.py", line 161, in get_recognizer
    model.load_state_dict(torch.load(model_path, map_location=device))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	size mismatch for module.Prediction.weight: copying a param with shape torch.Size([5381, 512]) from checkpoint, the shape in current model is torch.Size([3111, 512]).
	size mismatch for module.Prediction.bias: copying a param with shape torch.Size([5381]) from checkpoint, the shape in current model is torch.Size([3111]).

Process finished with exit code 1
```
Could you please help me to solve this error? Thanks in advance

**Comment by rkcosmos** [comment]
There was a typo in code, I just fixed it. Can you try reinstall the recent version and try again?

**Comment by freaky-geeky** [comment]
> There was a typo in code, I just fixed it. Can you try reinstall the recent version and try again?

Now Easy_OCR works perfectly. Thank you so much
